"""initial schema

Revision ID: e3f9427a3fbf
Revises:
Create Date: 2026-05-22 15:06:21.946831

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3f9427a3fbf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patient_name", sa.String(length=200), nullable=False),
        sa.Column("lot", sa.String(length=10), nullable=True),
        sa.Column("case_manager", sa.String(length=200), nullable=True),
        sa.Column("initial_contact_date", sa.Date(), nullable=True),
        sa.Column(
            "reason_for_exam",
            sa.Enum(
                "VOLUNTEER",
                "P1_TO_710",
                "P1_TO_720",
                "P1_TO_730",
                "CLUSTER_RELATED",
                "HEALTH_DEPT_REFERRAL",
                "NOT_YET_INTERVIEWED",
                "PRE_NATAL_SCREENING",
                "PT_REF",
                "SCREENING",
                "SELF_REFERRED",
                name="reason_for_exam_enum",
            ),
            nullable=True,
        ),
        sa.Column("treatment_date", sa.Date(), nullable=True),
        sa.Column("medical_info", sa.Text(), nullable=True),
        sa.Column(
            "lab_1",
            sa.Enum(
                "RPR_NEG",
                "RPR_REACTIVE",
                "RPR_1_1",
                "RPR_1_2",
                "RPR_1_4",
                "RPR_1_8",
                "RPR_1_16",
                "RPR_1_32",
                "RPR_1_64",
                "RPR_1_128",
                "RPR_1_256",
                "RPR_1_512",
                "RPR_1_1024",
                "RPR_GT_1024",
                "VDRL_NEG",
                "VDRL_REACTIVE",
                "VDRL_1_1",
                "VDRL_1_2",
                "VDRL_1_4",
                "VDRL_1_8",
                "VDRL_1_16",
                "VDRL_1_32",
                "VDRL_1_64",
                "VDRL_1_128",
                "VDRL_1_256",
                "VDRL_1_512",
                "VDRL_1_1024",
                "VDRL_GT_1024",
                name="lab_result_1_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "lab_2",
            sa.Enum(
                "TPPA_POS",
                "TPPA_NEG",
                "TP_AB_POS",
                "TP_AB_NEG",
                "DFKD_POS",
                "FTA_POS",
                "FTA_NEG",
                "MHATP",
                "OTHER",
                name="trep_result_enum",
            ),
            nullable=True,
        ),
        sa.Column("lab_3", sa.String(length=100), nullable=True),
        sa.Column(
            "treatment",
            sa.Enum(
                "RX_BIC_2_4",
                "RX_BIX_2_4_X3",
                "DOXY_100_14",
                "DOXY_100_28",
                "OTHER",
                name="treatment_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "lesion_type",
            sa.Enum(
                "ANAL",
                "LAB",
                "LX",
                "ORAL",
                "PENILE",
                "RECTAL",
                "VAGINAL",
                name="lesion_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "symptom",
            sa.Enum(
                "RASH", "PP_RASH", "GB_RASH", "C_LATA", "ALOPECIA", name="symptom_enum"
            ),
            nullable=True,
        ),
        sa.Column(
            "symptom_classification",
            sa.Enum("PRIMARY", "SECONDARY", name="symptom_class_enum"),
            nullable=True,
        ),
        sa.Column("symptom_onset_date", sa.Date(), nullable=True),
        sa.Column("symptom_duration_days", sa.Integer(), nullable=True),
        sa.Column("symptom_ongoing", sa.Boolean(), nullable=False),
        sa.Column("historical_primary_chancre", sa.Boolean(), nullable=True),
        sa.Column("historical_primary_date", sa.Date(), nullable=True),
        sa.Column("lab_1_date", sa.Date(), nullable=True),
        sa.Column("lab_2_date", sa.Date(), nullable=True),
        sa.Column("lab_3_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "arrow_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("from_ref", sa.String(length=20), nullable=False),
        sa.Column("to_ref", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ghostings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column(
            "ghosting_type",
            sa.Enum("SOURCE", "SPREAD_GHOST", "SPREAD", name="ghosting_type_enum"),
            nullable=False,
        ),
        sa.Column("from_ref", sa.String(length=20), nullable=True),
        sa.Column("to_ref", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "partners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("partner_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "reason_for_exam",
            sa.Enum(
                "VOLUNTEER",
                "P1_TO_710",
                "P1_TO_720",
                "P1_TO_730",
                "CLUSTER_RELATED",
                "HEALTH_DEPT_REFERRAL",
                "NOT_YET_INTERVIEWED",
                "PRE_NATAL_SCREENING",
                "PT_REF",
                "SCREENING",
                "SELF_REFERRED",
                name="partner_reason_enum",
            ),
            nullable=True,
        ),
        sa.Column("treatment_date", sa.Date(), nullable=True),
        sa.Column("medical_info", sa.Text(), nullable=True),
        sa.Column(
            "lab_1",
            sa.Enum(
                "RPR_NEG",
                "RPR_REACTIVE",
                "RPR_1_1",
                "RPR_1_2",
                "RPR_1_4",
                "RPR_1_8",
                "RPR_1_16",
                "RPR_1_32",
                "RPR_1_64",
                "RPR_1_128",
                "RPR_1_256",
                "RPR_1_512",
                "RPR_1_1024",
                "RPR_GT_1024",
                "VDRL_NEG",
                "VDRL_REACTIVE",
                "VDRL_1_1",
                "VDRL_1_2",
                "VDRL_1_4",
                "VDRL_1_8",
                "VDRL_1_16",
                "VDRL_1_32",
                "VDRL_1_64",
                "VDRL_1_128",
                "VDRL_1_256",
                "VDRL_1_512",
                "VDRL_1_1024",
                "VDRL_GT_1024",
                name="partner_lab1_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "lab_2",
            sa.Enum(
                "TPPA_POS",
                "TPPA_NEG",
                "TP_AB_POS",
                "TP_AB_NEG",
                "DFKD_POS",
                "FTA_POS",
                "FTA_NEG",
                "MHATP",
                "OTHER",
                name="partner_lab2_enum",
            ),
            nullable=True,
        ),
        sa.Column("lab_3", sa.String(length=100), nullable=True),
        sa.Column(
            "treatment",
            sa.Enum(
                "RX_BIC_2_4",
                "RX_BIX_2_4_X3",
                "DOXY_100_14",
                "DOXY_100_28",
                "OTHER",
                name="partner_treatment_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "lesion_type",
            sa.Enum(
                "ANAL",
                "LAB",
                "LX",
                "ORAL",
                "PENILE",
                "RECTAL",
                "VAGINAL",
                name="partner_lesion_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "symptom",
            sa.Enum(
                "RASH",
                "PP_RASH",
                "GB_RASH",
                "C_LATA",
                "ALOPECIA",
                name="partner_symptom_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "symptom_classification",
            sa.Enum("PRIMARY", "SECONDARY", name="p_symptom_class_enum"),
            nullable=True,
        ),
        sa.Column("symptom_onset_date", sa.Date(), nullable=True),
        sa.Column("symptom_duration_days", sa.Integer(), nullable=True),
        sa.Column("symptom_ongoing", sa.Boolean(), nullable=False),
        sa.Column("historical_primary_chancre", sa.Boolean(), nullable=True),
        sa.Column("historical_primary_date", sa.Date(), nullable=True),
        sa.Column("lab_1_date", sa.Date(), nullable=True),
        sa.Column("lab_2_date", sa.Date(), nullable=True),
        sa.Column("lab_3_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_partner_relationships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("exposure_first_date", sa.Date(), nullable=True),
        sa.Column("exposure_last_date", sa.Date(), nullable=True),
        sa.Column("exposure_modalities", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "partner_id", name="uq_case_partner_relationship"
        ),
    )
    op.create_table(
        "lab_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column(
            "test_category",
            sa.Enum("NON_TREPONEMAL", "TREPONEMAL", name="test_category_enum"),
            nullable=False,
        ),
        sa.Column("test_type", sa.String(length=100), nullable=False),
        sa.Column("titer", sa.String(length=100), nullable=True),
        sa.Column("result", sa.String(length=100), nullable=True),
        sa.Column("collection_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "map_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("item_number", sa.Integer(), nullable=False),
        sa.Column("p_value", sa.Boolean(), nullable=False),
        sa.Column("c_value", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("high_priority", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symptom_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("symptom_type", sa.String(length=100), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("PRIMARY", "SECONDARY", name="entry_symptom_class_enum"),
            nullable=True,
        ),
        sa.Column("onset_date", sa.Date(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("ongoing", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relationship_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("relationship_id", sa.Integer(), nullable=False),
        sa.Column("reporter", sa.String(length=100), nullable=False),
        sa.Column("exposure_first_date", sa.Date(), nullable=True),
        sa.Column("exposure_last_date", sa.Date(), nullable=True),
        sa.Column("exposure_modalities", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["case_partner_relationships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relationship_reports")
    op.drop_table("timeline_events")
    op.drop_table("symptom_entries")
    op.drop_table("map_entries")
    op.drop_table("lab_results")
    op.drop_table("case_partner_relationships")
    op.drop_table("partners")
    op.drop_table("ghostings")
    op.drop_table("arrow_links")
    op.drop_table("cases")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "entry_symptom_class_enum",
            "test_category_enum",
            "p_symptom_class_enum",
            "partner_symptom_enum",
            "partner_lesion_enum",
            "partner_treatment_enum",
            "partner_lab2_enum",
            "partner_lab1_enum",
            "partner_reason_enum",
            "ghosting_type_enum",
            "symptom_class_enum",
            "symptom_enum",
            "lesion_enum",
            "treatment_enum",
            "trep_result_enum",
            "lab_result_1_enum",
            "reason_for_exam_enum",
        ):
            postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
