FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY requirements/base.txt .
RUN pip install --no-cache-dir -r base.txt

COPY . .
RUN chmod +x /project/docker/entrypoint.sh
RUN pip install --no-cache-dir .

EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost:8000/health || exit 1

ENTRYPOINT ["/project/docker/entrypoint.sh"]
CMD ["uvicorn", "fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
